version: '3.4'

services:
  sasjs_server_api:
    image: sasjs_server_api
    build: ./api
    environment:
      MODE: server
      CORS: enable
      PORT: 5000
      DB_CONNECT: mongodb://mongodb:27017/sasjs
    ports:
      - 5000:5000
    volumes:
      - ./api:/usr/server/api
    links:
      - mongodb

  sasjs_server_web:
    image: sasjs_server_web
    build: ./web
    ports:
      - 3000:3000
    volumes:
      - ./web:/usr/server/web

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
  mongo-seed-users:
    build: ./mongo-seed/users
    links:
      - mongodb
  mongo-seed-clients:
    build: ./mongo-seed/clients
    links:
      - mongodb

volumes:
  data:
