name: SASjs Server Build

on:
  push:
  pull_request:

jobs:
  build-api:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        working-directory: ./api
        run: npm ci
      - name: Check Code Style
        working-directory: ./api
        run: npm run lint
      - name: Run Unit Tests
        working-directory: ./api
        run: npm test
      - name: Build Package
        working-directory: ./api
        run: npm run build
        env:
          CI: true
